### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by JoshuaYWang** [fireurza/WiseCracks#2]
![comedyclub](https://user-images.githubusercontent.com/29163474/26998704-86f39a30-4d4d-11e7-8481-dcb28cf106ae.jpg)

dont know what I'm doing wrong with the navbar. How do I make all the list items light up?

**Comment by fireurza** [comment]
Made changes to the css. Got it to glow on hover. The changes are made are in between the 2 comments. I can explain better if you need me to. Please double check.
