### ISSUE TITLE
I am having issues with the fonts and making the nav bar lay down and light as you scroll  on the icons.. any advice , help pretty please? 

### ISSUE THREAD

**Issue by jlitt007** [fireurza/WiseCracks#3]
I am still having issues with the nav bar making the bullets extend across the webpage. Does anyone have any idea how to link  the font style with the neon affect? I would like to like get some advice on linking the code with a video clip.  I am humble seeking your input and help in any form. thank you.

**Comment by fireurza** [comment]
Download the latest files for the project from github . I already made the navbar with the neon affect uniform across all the pages.
