### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by krystalwells** [fireurza/WiseCracks#4]
I need some help with CSS. I can't figure out how to make the map move to the right or of the screen, nor add show-card Gothic to the navbar. Any simple suggestions would be grateful. Please see attached files
[New Compressed (zipped) Folder.zip](https://github.com/fireurza/WiseCracks/files/1075745/New.Compressed.zipped.Folder.zip)

.

**Comment by fireurza** [comment]
I uploaded the css with the Showcard Gothic font. To add the Showcard gothic you need to create in css a link to the .ttf (font file) file and then call that link wherever you want to use it as a font. I added that to the css if you want to download the new project files and look at it. As for moving the map to the right, you need to assign a class or an id to the iframe that creates the map and then in css float it right. To fine tune the exact location after that you should be able to just add padding or margins to the iframe id in css.
