### ISSUE TITLE
Form Field

### ISSUE THREAD

**Issue by krystalwells** [fireurza/WiseCracks#5]
Any ideas as to how to make the form input fields, and submit button visible
[form input.zip](https://github.com/fireurza/WiseCracks/files/1078240/form.input.zip)

 over the background image?

Thanks

**Comment by fireurza** [comment]
to have the input seen on forms you should write it like:

<form>
       First Name:
      <input type="text" name="firstname" value="">
</form

you currently have it as a table (tr and td tags)
